spring:
  application:
    name: NutriShare

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy}
            scope:
              - profile
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID:dummy}
            client-secret: ${KAKAO_CLIENT_SECRET:dummy}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-your-256-bit-secret-your-256-bit-secret} # Must be 32+ chars
  access-token-validity-in-seconds: 1800 # 30 mins
  refresh-token-validity-in-seconds: 604800 # 7 days

app:
  qa:
    seed-enabled: true
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  oauth:
    kakao:
      admin-key: ${KAKAO_ADMIN_KEY:}
